import type { Course, StudentProfile, Requirement, CompletedCourse } from "./types"
import { HAVERFORD_COURSES } from './haverford-courses'

// Mock course catalog
export const mockCourses: any[] = HAVERFORD_COURSES.map(course => ({
  ...course,
  instructor: "Dr. Smith",
  meetingTimes: [
    { day: "Monday", startTime: "10:00", endTime: "11:00" },
    { day: "Wednesday", startTime: "10:00", endTime: "11:00" },
    { day: "Friday", startTime: "10:00", endTime: "11:00" },
  ],
  corequisites: [],
  semester: "Fall",
  year: 2024,
  maxEnrollment: 25,
  currentEnrollment: 15,
  location: "TBD",
})).concat([
  // Computer Science
  {
    id: "cs-101",
    code: "CMSC 101",
    title: "Introduction to Computer Science",
    description: "An introduction to the field of computer science, including programming fundamentals, problem-solving, and computational thinking.",
    credits: 4,
    department: "Computer Science",
    instructor: "Dr. Smith",
    meetingTimes: [
      { day: "Monday", startTime: "10:00", endTime: "11:00" },
      { day: "Wednesday", startTime: "10:00", endTime: "11:00" },
      { day: "Friday", startTime: "10:00", endTime: "11:00" },
    ],
    prerequisites: [],
    corequisites: [],
    fulfills: ["Major Core", "Quantitative"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 30,
    currentEnrollment: 22,
    location: "Stokes Hall 240",
  },
  {
    id: "cs-201",
    code: "CMSC 201",
    title: "Data Structures",
    description: "Study of fundamental data structures including arrays, linked lists, stacks, queues, trees, and graphs. Analysis of algorithms.",
    credits: 4,
    department: "Computer Science",
    instructor: "Dr. Johnson",
    meetingTimes: [
      { day: "Tuesday", startTime: "13:00", endTime: "14:30" },
      { day: "Thursday", startTime: "13:00", endTime: "14:30" },
    ],
    prerequisites: ["cs-101"],
    corequisites: [],
    fulfills: ["Major Core"],
    semester: "Spring",
    year: 2025,
    maxEnrollment: 25,
    currentEnrollment: 18,
    location: "Stokes Hall 142",
  },
  {
    id: "cs-245",
    code: "CMSC 245",
    title: "Database Systems",
    description: "Introduction to database design, SQL, normalization, and database management systems.",
    credits: 4,
    department: "Computer Science",
    instructor: "Dr. Martinez",
    meetingTimes: [
      { day: "Monday", startTime: "14:00", endTime: "15:30" },
      { day: "Wednesday", startTime: "14:00", endTime: "15:30" },
    ],
    prerequisites: ["cs-201"],
    corequisites: [],
    fulfills: ["Major Elective"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 20,
    currentEnrollment: 15,
    location: "Stokes Hall 003",
  },
  {
    id: "cs-280",
    code: "CMSC 280",
    title: "Web Development",
    description: "Modern web development with HTML, CSS, JavaScript, and popular frameworks. Full-stack development principles.",
    credits: 4,
    department: "Computer Science",
    instructor: "Prof. Chen",
    meetingTimes: [
      { day: "Tuesday", startTime: "10:00", endTime: "11:30" },
      { day: "Thursday", startTime: "10:00", endTime: "11:30" },
    ],
    prerequisites: ["cs-101"],
    corequisites: [],
    fulfills: ["Major Elective"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 24,
    currentEnrollment: 24,
    location: "KINSC L108",
  },

  // Mathematics
  {
    id: "math-121",
    code: "MATH 121",
    title: "Calculus I",
    description: "Limits, derivatives, integrals, and applications. Fundamental theorem of calculus.",
    credits: 4,
    department: "Mathematics",
    instructor: "Dr. Williams",
    meetingTimes: [
      { day: "Monday", startTime: "09:00", endTime: "10:00" },
      { day: "Wednesday", startTime: "09:00", endTime: "10:00" },
      { day: "Friday", startTime: "09:00", endTime: "10:00" },
    ],
    prerequisites: [],
    corequisites: [],
    fulfills: ["Quantitative", "Natural Sciences"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 35,
    currentEnrollment: 28,
    location: "Sharpless Hall S102",
  },
  {
    id: "math-215",
    code: "MATH 215",
    title: "Linear Algebra",
    description: "Vector spaces, linear transformations, matrices, eigenvalues, and eigenvectors.",
    credits: 4,
    department: "Mathematics",
    instructor: "Dr. Taylor",
    meetingTimes: [
      { day: "Tuesday", startTime: "11:00", endTime: "12:30" },
      { day: "Thursday", startTime: "11:00", endTime: "12:30" },
    ],
    prerequisites: ["math-121"],
    corequisites: [],
    fulfills: ["Quantitative"],
    semester: "Spring",
    year: 2025,
    maxEnrollment: 30,
    currentEnrollment: 25,
    location: "Sharpless Hall S002",
  },

  // English
  {
    id: "engl-101",
    code: "ENGL 101",
    title: "College Writing",
    description: "Development of critical reading and writing skills. Focus on argument, analysis, and research.",
    credits: 3,
    department: "English",
    instructor: "Prof. Anderson",
    meetingTimes: [
      { day: "Monday", startTime: "13:00", endTime: "14:30" },
      { day: "Wednesday", startTime: "13:00", endTime: "14:30" },
    ],
    prerequisites: [],
    corequisites: [],
    fulfills: ["Writing", "Humanities"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 18,
    currentEnrollment: 16,
    location: "Stokes Hall 105",
  },
  {
    id: "engl-235",
    code: "ENGL 235",
    title: "American Literature",
    description: "Survey of American literature from colonial period to present. Major authors and movements.",
    credits: 3,
    department: "English",
    instructor: "Prof. Roberts",
    meetingTimes: [
      { day: "Tuesday", startTime: "14:30", endTime: "16:00" },
      { day: "Thursday", startTime: "14:30", endTime: "16:00" },
    ],
    prerequisites: [],
    corequisites: [],
    fulfills: ["Humanities"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 20,
    currentEnrollment: 12,
    location: "Stokes Hall 223",
  },

  // Biology
  {
    id: "biol-100",
    code: "BIOL 100",
    title: "Introduction to Biology",
    description: "Fundamental concepts in biology including cell structure, genetics, evolution, and ecology.",
    credits: 4,
    department: "Biology",
    instructor: "Dr. Lee",
    meetingTimes: [
      { day: "Monday", startTime: "11:00", endTime: "12:00" },
      { day: "Wednesday", startTime: "11:00", endTime: "12:00" },
      { day: "Friday", startTime: "14:00", endTime: "17:00" },
    ],
    prerequisites: [],
    corequisites: [],
    fulfills: ["Natural Sciences"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 24,
    currentEnrollment: 20,
    location: "Sharpless Hall W201 / Lab: KINSC",
  },

  // Psychology
  {
    id: "psyc-100",
    code: "PSYC 100",
    title: "Introduction to Psychology",
    description: "Overview of psychological science including cognition, development, social psychology, and mental health.",
    credits: 3,
    department: "Psychology",
    instructor: "Dr. Garcia",
    meetingTimes: [
      { day: "Tuesday", startTime: "09:00", endTime: "10:30" },
      { day: "Thursday", startTime: "09:00", endTime: "10:30" },
    ],
    prerequisites: [],
    corequisites: [],
    fulfills: ["Social Sciences"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 40,
    currentEnrollment: 35,
    location: "Stokes Hall Auditorium",
  },

  // Economics
  {
    id: "econ-101",
    code: "ECON 101",
    title: "Principles of Microeconomics",
    description: "Introduction to microeconomic theory, including supply and demand, market structures, and consumer behavior.",
    credits: 3,
    department: "Economics",
    instructor: "Prof. Brown",
    meetingTimes: [
      { day: "Monday", startTime: "15:30", endTime: "17:00" },
      { day: "Wednesday", startTime: "15:30", endTime: "17:00" },
    ],
    prerequisites: [],
    corequisites: [],
    fulfills: ["Social Sciences"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 35,
    currentEnrollment: 30,
    location: "Sharpless Hall S105",
  },

  // Philosophy
  {
    id: "phil-101",
    code: "PHIL 101",
    title: "Introduction to Philosophy",
    description: "Exploration of fundamental philosophical questions about knowledge, reality, ethics, and existence.",
    credits: 3,
    department: "Philosophy",
    instructor: "Dr. Wilson",
    meetingTimes: [
      { day: "Tuesday", startTime: "13:00", endTime: "14:30" },
      { day: "Thursday", startTime: "13:00", endTime: "14:30" },
    ],
    prerequisites: [],
    corequisites: [],
    fulfills: ["Humanities"],
    semester: "Fall",
    year: 2024,
    maxEnrollment: 25,
    currentEnrollment: 18,
    location: "Stokes Hall 201",
  },

  // Spring Semester Courses
  {
    id: "cs-310",
    code: "CMSC 310",
    title: "Algorithms",
    description: "Design and analysis of algorithms. Divide-and-conquer, dynamic programming, greedy algorithms, and NP-completeness.",
    credits: 4,
    department: "Computer Science",
    instructor: "Dr. Smith",
    meetingTimes: [
      { day: "Monday", startTime: "10:00", endTime: "11:30" },
      { day: "Wednesday", startTime: "10:00", endTime: "11:30" },
    ],
    prerequisites: ["cs-201"],
    corequisites: [],
    fulfills: ["Major Core"],
    semester: "Spring",
    year: 2025,
    maxEnrollment: 25,
    currentEnrollment: 0,
    location: "Stokes Hall 240",
  },
  {
    id: "cs-360",
    code: "CMSC 360",
    title: "Artificial Intelligence",
    description: "Introduction to AI including search, knowledge representation, machine learning, and neural networks.",
    credits: 4,
    department: "Computer Science",
    instructor: "Dr. Martinez",
    meetingTimes: [
      { day: "Tuesday", startTime: "14:30", endTime: "16:00" },
      { day: "Thursday", startTime: "14:30", endTime: "16:00" },
    ],
    prerequisites: ["cs-201", "math-215"],
    corequisites: [],
    fulfills: ["Major Elective"],
    semester: "Spring",
    year: 2025,
    maxEnrollment: 20,
    currentEnrollment: 0,
    location: "KINSC L108",
  },
])

// Mock student profile
export const mockStudentProfile: StudentProfile = {
  id: "student-001",
  name: "Alex Johnson",
  email: "ajohnson@haverford.edu",
  major: "Computer Science",
  minor: "Mathematics",
  currentYear: 2,
  currentSemester: "Fall",
  expectedGraduation: {
    semester: "Spring",
    year: 2027,
  },
  advisor: "Dr. Smith",
  completedCourses: [
    {
      courseId: "cs-101",
      courseCode: "CMSC 101",
      courseTitle: "Introduction to Computer Science",
      credits: 4,
      semester: "Fall",
      year: 2023,
      grade: "A",
      fulfills: ["Major Core", "Quantitative"],
    },
    {
      courseId: "math-121",
      courseCode: "MATH 121",
      courseTitle: "Calculus I",
      credits: 4,
      semester: "Fall",
      year: 2023,
      grade: "A-",
      fulfills: ["Quantitative", "Natural Sciences"],
    },
    {
      courseId: "engl-101",
      courseCode: "ENGL 101",
      courseTitle: "College Writing",
      credits: 3,
      semester: "Spring",
      year: 2024,
      grade: "B+",
      fulfills: ["Writing", "Humanities"],
    },
    {
      courseId: "cs-201",
      courseCode: "CMSC 201",
      courseTitle: "Data Structures",
      credits: 4,
      semester: "Spring",
      year: 2024,
      grade: "A",
      fulfills: ["Major Core"],
    },
  ],
  totalCreditsCompleted: 15,
}

// Mock requirements for Computer Science major
export const mockRequirements: Requirement[] = [
  {
    id: "req-cs-core",
    category: "Major Core",
    description: "Core Computer Science courses",
    creditsRequired: 20,
    creditsCompleted: 8,
    coursesRequired: 5,
    coursesCompleted: 2,
    specificCourses: ["cs-101", "cs-201", "cs-310", "cs-245", "cs-360"],
    completed: false,
  },
  {
    id: "req-cs-elective",
    category: "Major Elective",
    description: "Computer Science electives",
    creditsRequired: 12,
    creditsCompleted: 0,
    coursesRequired: 3,
    coursesCompleted: 0,
    completed: false,
  },
  {
    id: "req-quantitative",
    category: "Quantitative",
    description: "Quantitative reasoning requirement",
    creditsRequired: 8,
    creditsCompleted: 8,
    completed: true,
  },
  {
    id: "req-natural-sci",
    category: "Natural Sciences",
    description: "Natural sciences requirement",
    creditsRequired: 8,
    creditsCompleted: 4,
    completed: false,
  },
  {
    id: "req-humanities",
    category: "Humanities",
    description: "Humanities requirement",
    creditsRequired: 6,
    creditsCompleted: 3,
    completed: false,
  },
  {
    id: "req-social-sci",
    category: "Social Sciences",
    description: "Social sciences requirement",
    creditsRequired: 6,
    creditsCompleted: 0,
    completed: false,
  },
  {
    id: "req-writing",
    category: "Writing",
    description: "Writing requirement",
    creditsRequired: 3,
    creditsCompleted: 3,
    completed: true,
  },
]
